# Generated by Django 5.2.6 on 2025-11-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_detallecompra_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='terminal_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='terminal_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
