# Generated by Django 5.2.6 on 2025-11-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_usuario_creado_en_usuario_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='recovery_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='recovery_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
