# Generated by Django 5.2.6 on 2025-11-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usuario_recovery_token_usuario_recovery_token_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
