# Generated by Django 5.2.6 on 2025-11-19 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_producto_codigo_barra'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(default='N/A', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
