# Generated by Django 5.2.6 on 2025-11-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'administrador'), ('dueno', 'Dueño'), ('cajero', 'Cajero'), ('usuario', 'Usuario')], default='usuario', max_length=20),
        ),
    ]
