# Generated by Django 5.2.6 on 2025-11-24 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('tuu', 'Tuu'), ('compraqui', 'Compraqui')], max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='folio',
            field=models.PositiveIntegerField(blank=True, help_text='Folio incremental por máquina', null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='maquina',
            field=models.ForeignKey(blank=True, help_text='Máquina asociada: Tuu o Compraqui', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.maquina'),
        ),
        migrations.AddField(
            model_name='venta',
            name='maquina',
            field=models.ForeignKey(blank=True, help_text='Máquina asociada: Tuu o Compraqui', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.maquina'),
        ),
        migrations.AlterUniqueTogether(
            name='venta',
            unique_together={('maquina', 'folio')},
        ),
    ]
