# Generated by Django 5.2.6 on 2025-12-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_caja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=1500000, max_digits=12)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
