# Generated by Django 5.2.6 on 2025-12-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriagasto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoriagasto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
