# Generated by Django 5.2.6 on 2025-12-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_categoriagasto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
